# This is a basic workflow to help you get started with Actions

name: Sync-Images-to-DockerHub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      # Runs a set of commands using the runners shell
      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Use Skopeo Tools Sync Image to Docker Hub
        run: |
          #!/usr/bin/env bash
          # frooodle/s-pdf:latest
          # skopeo copy docker://docker.io/frooodle/s-pdf:latest docker://registry.cn-hangzhou.aliyuncs.com/linc-soft/s-pdf:latest
          # ubuntu/nginx:latest
          # skopeo copy docker://docker.io/ubuntu/nginx:latest docker://registry.cn-hangzhou.aliyuncs.com/linc-soft/ubuntu-nginx:latest
          # dreamacro/clash
          # skopeo copy docker://docker.io/dreamacro/clash:latest docker://registry.cn-hangzhou.aliyuncs.com/linc-soft/dreamacro-clash:latest
          # haishanh/yacd
          # skopeo copy docker://docker.io/haishanh/yacd:latest docker://registry.cn-hangzhou.aliyuncs.com/linc-soft/haishanh-yacd:latest
          # rabbitmq
          # skopeo copy docker://docker.io/library/rabbitmq:3.13-management docker://registry.cn-hangzhou.aliyuncs.com/linc-soft/rabbitmq:3.13-management
          # ubuntu:22.04
          # skopeo copy docker://docker.io/library/ubuntu:22.04 docker://registry.cn-hangzhou.aliyuncs.com/linc-soft/ubuntu:22.04
          # Nginx
          # skopeo copy docker://docker.io/library/nginx:latest docker://registry.cn-hangzhou.aliyuncs.com/linc-soft/nginx:latest
          # R
          # skopeo copy docker://docker.io/rocker/rstudio:latest docker://registry.cn-hangzhou.aliyuncs.com/linc-soft/rocker-rstudio:latest
          # 
          skopeo copy docker://docker.io/openp2pcn/openp2p-client:latest docker://registry.cn-hangzhou.aliyuncs.com/linc-soft/openp2p-client:latest
